### ISSUE TITLE
Errors with fs-store.lisp read-internal

### ISSUE THREAD

**Issue by bobbysmith007** [skypher/montezuma#4]
What steps will reproduce the problem?
1. Load a file system index
2. try to query it

What is the expected output? What do you see instead?
It should return results, instead I get an EOF error

What version of the product are you using? On what operating system?
As far as I know I am using the latest version (it was the quicklisp version that was giving me issues)

Please provide any additional information below.
From the docs for read-sequence "the index of the next element is returned".  (read-sequence ...) returns the position in the file rather than the number of bytes read. 

If I change (unless (= num-bytes-read length)...) to (unless (= num-bytes-read end)...), then I don't get errors and I can successfully query the index.

The specific patch:
https://github.com/AccelerationNet/montezuma/commit/0b22ec053234a79868f1486c4f35482e10d3f37c

All my error fixing patchs:
https://github.com/AccelerationNet/montezuma/commits/accel-error-fixing

**Comment by skypher** [comment]
Thanks! Please send a pull request.

**Comment by bobbysmith007** [comment]
I wish I could, unfortunately since my github repo predates this one, there doesn't seem to be a way without deleting it and recreating the repo.  

I can do this, but if you already have a local clone, you could simply do something like

```
git remote add acceleration git://github.com/AccelerationNet/montezuma.git
git fetch acceleration
git merge acceleration/accel-error-fixing
```

Which will accomplish the same things.  Please let me know if you need me to recreate my github repo.

**Comment by skypher** [comment]
> I wish I could, unfortunately since my github repo predates this one,
> there doesn't seem to be a way without deleting it and recreating the
> repo.
> 
> I can do this, but if you already have a local clone, you could simply do
> something like
> 
> ```
> git remote add acceleration git://github.com/AccelerationNet/montezuma.git
> git fetch acceleration
> git merge acceleration/accel-error-fixing
> ```
> 
> Which will accomplish the same things.  Please let me know if you need me
> to recreate my github repo.

That would be great!

  Leslie

**Comment by bobbysmith007** [comment]
There is a pull request as issue #7 so I am closing this.
